import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<div className="flex items-center justify-center h-screen">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1 className="text-4xl font-bold underline text-yellow-500 font-mono">
					Erq-Maed API List
				</h1>

				<ul className="mt-8 space-y-2">
					<li className="text-2xl font-semibold  text-sky-700 ">
						<a className="text-amber-500 hover:text-sky-500"  href="/api/aboutus">/api/about us</a>
					</li>
					<li className="text-2xl font-semibold  text-sky-700 ">
						<a className="text-amber-500 hover:text-sky-500"  href="	/api/blog"> /api/blog</a>
					</li>
					<li className="text-2xl font-semibold  text-sky-700 ">
						<a className="text-amber-500 hover:text-sky-500"  href="	/api/homepage"> /api/homepage</a>
					</li>
					<li className="text-2xl font-semibold  text-sky-700 ">
						<a className="text-amber-500 hover:text-sky-500"  href="	/api/portfolio"> /api/portfolio</a>
					</li>
					<li className="text-2xl font-semibold  text-sky-700 ">
						<a className="text-amber-500 hover:text-sky-500"  href="	/api/radio"> /api/radio</a>
					</li>
					<li className="text-2xl font-semibold  text-sky-700 ">
						<a className="text-amber-500 hover:text-sky-500"  href="	/api/servicedata"> /api/servicedata</a>
					</li>
					<li className="text-2xl font-semibold  text-sky-700 ">
						<a className="text-amber-500 hover:text-sky-500"  href="	/api/upcoming"> /api/upcoming</a>
					</li>
				</ul>
			</main>
		</div>
	);
}
